### ISSUE TITLE
想知道remove 移动目标的那一部分是怎么完成的

### ISSUE THREAD

**Issue by ybyzy** [YJZLuckyBoy/liorf#1]

**Comment by YJZLuckyBoy** [comment]
使用最简单的聚类算法就可以实现，但是精度有待提高

**Comment by ybyzy** [comment]
> 使用最简单的聚类算法就可以实现，但是精度有待提高

聚类算法也不能识别是否为动态吧？这是怎么一种实现呢？谢谢你的回复。

**Comment by YJZLuckyBoy** [comment]
> 



> > 使用最简单的聚类算法就可以实现，但是精度有待提高
> 
> 聚类算法也不能识别是否为动态吧？这是怎么一种实现呢？谢谢你的回复。

可以基于一个强假设，可以参考lio-livox
