### ISSUE TITLE
[liorf_imuPreintegration-2] process has died 

### ISSUE THREAD

**Issue by J-alchemist** [YJZLuckyBoy/liorf#10]
terminate called after throwing an instance of 'gtsam::IndeterminantLinearSystemException'
  what():  
Indeterminant linear system detected while working near variable
8646911284551352339 (Symbol: x19).

Thrown when a linear system is ill-posed.  The most common cause for this
error is having underconstrained variables.  Mathematically, the system is
underdetermined.  See the GTSAM Doxygen documentation at
http://borg.cc.gatech.edu/ on gtsam::IndeterminantLinearSystemException for
more information.
124644
[liorf_imuPreintegration-2] process has died 

when I Run kitti dataset

**Comment by tiesus** [comment]
Was the problem solved by using  gtsam 4.0.2? <br>

If yes, maybe the install instructions should be updated?
