### ISSUE TITLE
Support for ros2 

### ISSUE THREAD

**Issue by Zermelo-101** [YJZLuckyBoy/liorf#11]
We are using an Ouster lidar, with the integrated 6 axis IMU, and we want to use  ROS 2 LIO SAM to have a reliable odometry. We tried to simulate a 9 axis IMU but we failed so we decided to use your package. What did you do to make LIO SAM work with a ouster lidar so that we can implement it in Ros 2.
Thank you

**Comment by YJZLuckyBoy** [comment]
The liorf and lio-sam frameworks are completely consistent, so you can refer to the ROS2 version of lio-sam for modifications.
