### ISSUE TITLE
关于6轴imu的问题

### ISSUE THREAD

**Issue by zhuzy-2018** [YJZLuckyBoy/liorf#2]
你好想请问一下，从LIO-SAM主要是哪里需要依赖9轴imu呢？
如果我也想魔改LIO-SAM使其适配6轴imu，应该修改代码中的哪些地方呢

**Comment by YJZLuckyBoy** [comment]
> 你好想请问一下，从LIO-SAM主要是哪里需要依赖9轴imu呢？ 如果我也想魔改LIO-SAM使其适配6轴imu，应该修改代码中的哪些地方呢

主要是系统初始化还有位姿预测方面的，具体更改你可以看一下我改的这版，希望对你有所帮助
