### ISSUE TITLE
License

### ISSUE THREAD

**Issue by bluecamel** [YJZLuckyBoy/liorf#21]
Thanks for the great project!

There isn't currently a license and, according to GitHub (https://choosealicense.com/no-permission/#for-users), no one is allowed to use or modify this project.

Would you please consider adding a license?  LIO-SAM uses the BSD-3-Clause license, but MIT is another great option.

Thanks so much!

**Comment by YJZLuckyBoy** [comment]
Thanks for your suggestion. I have added the MIT license.

**Comment by bluecamel** [comment]
Sorry, I missed this update, but thank you so much!
