### ISSUE TITLE
OS1-128 Internal IMU

### ISSUE THREAD

**Issue by CantLooseToAMoose** [YJZLuckyBoy/liorf#41]
When using the Ouster's internal IMU I get a `Large velocity, reset IMU-preintegration!` warning.
It also seems like the sensors position is jumping around when trying to construct the map.
How would I set it up to work with an internal IMU the right way? I used the `run_lio_sam_ouster.launch` file and did not change the config file.

![image](https://github.com/YJZLuckyBoy/liorf/assets/72610590/5802f55f-7f4e-4e6e-ada2-e3814091d58f)

**Comment by ZhangYaoll** [comment]
Try to change imuRate from 500 to 100, because ouster imu rate is 100. Besides, extrinsicRot should change to [-1,0,0,0,-1,0,0,0,1]. Good luck.

**Comment by CantLooseToAMoose** [comment]
> Try to change imuRate from 500 to 100, because ouster imu rate is 100. Besides, extrinsicRot should change to [-1,0,0,0,-1,0,0,0,1]. Good luck.

Sadly I tried that already..

**Comment by CantLooseToAMoose** [comment]
Turns out my recorded bag file was from a really tight indoor space and I had to reduce the voxel size significantly lower to something like 0.1 for the algorithm to work.
