### ISSUE TITLE
使用自己的配置，加入gps因子后飞掉了

### ISSUE THREAD

**Issue by zhuzy-2018** [YJZLuckyBoy/liorf#9]
我使用自己的配置，在只使用LIO时，效果非常好。
但是加入gps后，就产生特别大的偏差，整个飞掉了
并且显示：Large velocity, reset IMU-preintegration!
![Screenshot from 2023-02-25 17-50-32](https://user-images.githubusercontent.com/42018599/221350899-811d614a-06fb-4415-99b3-6d17c70885ad.png)

请问作者有没有遇到过类似的情况，有没有什么头绪？

**Comment by zhuzy-2018** [comment]
解决了，是我自己做GPS变换到局部坐标系的时候数值太大了，然后gtsam可能优化误差变得很大。减掉一个固定偏差就好了。
顺便一提，gps_factor()函数的第一个判断应该改成
gpsMsg->status.status == -1

**Comment by lonlonago** [comment]
> 解决了，是我自己做GPS变换到局部坐标系的时候数值太大了，然后gtsam可能优化误差变得很大。减掉一个固定偏差就好了。 顺便一提，gps_factor()函数的第一个判断应该改成 gpsMsg->status.status == -1

@zhuzy-2018 请问你是怎么加的GPS，自己先把GPS变换到局部坐标系吗？还是直接就用的作者的代码，另外GPS和雷达的外参写在哪里的呢  期待你的回复
